//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_management_and_notes
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    
    public partial class LoginInfo
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> ProjectId { get; set; }
    
        public virtual Project Project { get; set; }

        public override string ToString()
        {
            return Url;
        }

        internal string toBackUpFormat()
        {
            StringBuilder sb = new StringBuilder();

            sb.Append(Id + " ");
            sb.Append(ProjectId + " ");
            sb.Append(Url + " ");
            sb.Append(Username + " ");
            sb.Append(Password + Environment.NewLine);

            return sb.ToString();
        }
    }
}
